"""Fake SDK clients for provider tests: they record every call and replay scripted replies.

The replies are real SDK objects (messages, exceptions ...) built by the helpers below, so the
adapters are tested against the SDKs' actual types. SDKs are imported inside the helpers, which
keeps this module importable when the extras are not installed.
"""

from __future__ import annotations

import threading
from types import SimpleNamespace
from typing import Any


class Recorder:
    """Stands in for one SDK method: records its keyword arguments and replays ``replies``.

    Replies are served in order and the last one repeats forever; exceptions are raised.
    """

    def __init__(self, *replies: object) -> None:
        self.calls: list[dict[str, Any]] = []
        self._replies = list(replies)
        self._lock = threading.Lock()

    def __call__(self, **kwargs: Any) -> Any:
        with self._lock:
            self.calls.append(kwargs)
            reply = self._replies.pop(0) if len(self._replies) > 1 else self._replies[0]
        if isinstance(reply, BaseException):
            raise reply
        return reply


class FakeAnthropic:
    """Stands in for ``anthropic.Anthropic``: only ``messages.create`` exists."""

    def __init__(self, *replies: object) -> None:
        self.create = Recorder(*replies)
        self.messages = SimpleNamespace(create=self.create)


def claude_message(
    text: str, *, stop_reason: str = "end_turn", thinking: bool = False, refusal: str | None = None
) -> Any:
    """A real ``anthropic.types.Message`` whose text blocks hold ``text``."""
    from anthropic.types import Message, RefusalStopDetails, TextBlock, ThinkingBlock, Usage

    content: list[Any] = []
    if thinking:
        content.append(ThinkingBlock(type="thinking", thinking="", signature="sig"))
    if text:
        content.append(TextBlock(type="text", text=text))
    details = RefusalStopDetails(type="refusal", category=refusal) if refusal else None
    return Message(
        id="msg_test",
        type="message",
        role="assistant",
        model="claude-opus-5",
        content=content,
        stop_reason=stop_reason,
        stop_details=details,
        usage=Usage(input_tokens=10, output_tokens=10),
    )


def api_error(sdk: Any, name: str, status: int = 0, message: str = "boom") -> Exception:
    """A real exception of the Anthropic or OpenAI SDK (both generated by Stainless)."""
    import httpx2

    request = httpx2.Request("POST", "https://api.example.com/v1")
    cls = getattr(sdk, name)
    if name == "APITimeoutError":
        error = cls(request=request)
    elif name == "APIConnectionError":
        error = cls(message=message, request=request)
    else:
        error = cls(message, response=httpx2.Response(status, request=request), body=None)
    return error
